// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBT3-KjnmjoTY8C6X6SN8_hkSqIosQRzg',
    appId: '1:1016843338354:web:929416a68c59a38d85f8eb',
    messagingSenderId: '1016843338354',
    projectId: 'gen-lang-client-0608619872',
    authDomain: 'gen-lang-client-0608619872.firebaseapp.com',
    storageBucket: 'gen-lang-client-0608619872.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCybGW-5PHDEKYPo1eU4QD0gcYVQ03rlm0',
    appId: '1:1016843338354:android:35d38e16a16442e485f8eb',
    messagingSenderId: '1016843338354',
    projectId: 'gen-lang-client-0608619872',
    storageBucket: 'gen-lang-client-0608619872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyyaAvVQailcCuc0DUe8roTOx3d3wHStE',
    appId: '1:1016843338354:ios:cb39c7ca8f63f7da85f8eb',
    messagingSenderId: '1016843338354',
    projectId: 'gen-lang-client-0608619872',
    storageBucket: 'gen-lang-client-0608619872.firebasestorage.app',
    iosClientId: '1016843338354-jfvdnj1qcup0vc0d8t6c4j3h34tdjket.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyyaAvVQailcCuc0DUe8roTOx3d3wHStE',
    appId: '1:1016843338354:ios:cb39c7ca8f63f7da85f8eb',
    messagingSenderId: '1016843338354',
    projectId: 'gen-lang-client-0608619872',
    storageBucket: 'gen-lang-client-0608619872.firebasestorage.app',
    iosClientId: '1016843338354-jfvdnj1qcup0vc0d8t6c4j3h34tdjket.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBT3-KjnmjoTY8C6X6SN8_hkSqIosQRzg',
    appId: '1:1016843338354:web:892d18cd2c46f4e185f8eb',
    messagingSenderId: '1016843338354',
    projectId: 'gen-lang-client-0608619872',
    authDomain: 'gen-lang-client-0608619872.firebaseapp.com',
    storageBucket: 'gen-lang-client-0608619872.firebasestorage.app',
  );
}
